### ISSUE TITLE
Missing units (px, em) in generated CSS

### ISSUE THREAD

**Issue by wolfy1339** [idleberg/m8tro-bootstrap#2]
In various places in the generated CSS they is missing the unit of measurement. 
I believe you need to add it in the less files, specifically variables.less.
Example from .container-fluid: 
```css
.container-fluid {
margin-right: auto;
margin-left: auto;
padding-left: 10;
padding-right: 10;
}
```
